import type { TrendingAnalytics, TrendingFilters } from "@/types/trending";

export class TrendingMockApi {
  async getTrendingAnalytics(filters: TrendingFilters): Promise<TrendingAnalytics> {
    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 700));

    return {
      hashtags: [
        {
          id: "1",
          tag: "#foodie",
          mentions: 1250,
          growth: 45.2,
          category: "food",
          platforms: ["Instagram", "TikTok", "Twitter"],
          sentiment: "positive",
        },
        {
          id: "2",
          tag: "#restaurant",
          mentions: 890,
          growth: 32.1,
          category: "general",
          platforms: ["Facebook", "Instagram"],
          sentiment: "positive",
        },
        {
          id: "3",
          tag: "#pasta",
          mentions: 567,
          growth: 78.5,
          category: "food",
          platforms: ["TikTok", "Instagram"],
          sentiment: "positive",
        },
        {
          id: "4",
          tag: "#datenight",
          mentions: 445,
          growth: 23.7,
          category: "experience",
          platforms: ["Instagram", "Facebook"],
          sentiment: "positive",
        },
        {
          id: "5",
          tag: "#delicious",
          mentions: 389,
          growth: 56.3,
          category: "food",
          platforms: ["Instagram", "TikTok"],
          sentiment: "positive",
        },
        {
          id: "6",
          tag: "#service",
          mentions: 234,
          growth: 12.8,
          category: "service",
          platforms: ["Google Reviews", "Facebook"],
          sentiment: "neutral",
        },
      ],
      topics: [
        {
          id: "1",
          topic: "Signature Pasta Dish",
          mentions: 234,
          sentiment: "positive",
          growth: 67.5,
          platforms: ["Instagram", "TikTok", "Facebook"],
          description: "Customers are raving about the new signature pasta dish",
          keywords: ["pasta", "signature", "delicious", "amazing"],
          relatedHashtags: ["#pasta", "#signature", "#delicious"],
        },
        {
          id: "2",
          topic: "Weekend Brunch Menu",
          mentions: 189,
          sentiment: "positive",
          growth: 45.2,
          platforms: ["Instagram", "Facebook"],
          description: "The weekend brunch menu is gaining popularity",
          keywords: ["brunch", "weekend", "menu", "popular"],
          relatedHashtags: ["#brunch", "#weekend", "#menu"],
        },
        {
          id: "3",
          topic: "Outdoor Seating",
          mentions: 156,
          sentiment: "positive",
          growth: 34.8,
          platforms: ["Google Reviews", "TripAdvisor"],
          description: "Customers love the new outdoor seating area",
          keywords: ["outdoor", "seating", "patio", "atmosphere"],
          relatedHashtags: ["#outdoor", "#patio", "#atmosphere"],
        },
        {
          id: "4",
          topic: "Wait Times",
          mentions: 98,
          sentiment: "negative",
          growth: 23.1,
          platforms: ["Google Reviews", "Facebook"],
          description: "Some concerns about wait times during peak hours",
          keywords: ["wait", "slow", "service", "peak"],
          relatedHashtags: ["#service", "#wait", "#slow"],
        },
      ],
      viralContent: [
        {
          id: "1",
          platform: "TikTok",
          content: "Chef reveals secret ingredient in viral pasta recipe",
          views: 125000,
          likes: 8900,
          shares: 1200,
          comments: 567,
          growth: 234.5,
          date: "2025-01-14",
          contentType: "video",
        },
        {
          id: "2",
          platform: "Instagram",
          content: "Behind-the-scenes: Morning prep in our kitchen",
          views: 45000,
          likes: 3400,
          shares: 890,
          comments: 234,
          growth: 156.7,
          date: "2025-01-13",
          contentType: "image",
        },
        {
          id: "3",
          platform: "Facebook",
          content: "Customer surprise birthday celebration",
          views: 23000,
          likes: 1200,
          shares: 345,
          comments: 89,
          growth: 89.3,
          date: "2025-01-12",
          contentType: "video",
        },
      ],
      category: filters.category,
      timeframe: filters.timeframe,
    };
  }
}

export const trendingMockApi = new TrendingMockApi();
